# Site settings
title: Thomas Brunner
email: brunner.thom@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Personal web site of Thomas Brunner, graduate from the University of St Andrews and the Technical University of Munich.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tuomasi.github.io" # the base hostname & protocol for your site
twitter_username:
github_username:  tuomasi

# Build settings
markdown: kramdown
